[2024-05-19 17:45:55,062][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=100, round_timeout=None)
[2024-05-19 17:45:57,106][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 83275839284.0, 'GPU': 2.0, 'node:172.17.34.3': 1.0, 'accelerator_type:G': 1.0, 'object_store_memory': 39975359692.0, 'CPU': 24.0}
[2024-05-19 17:45:57,106][flwr][INFO] - Initializing global parameters
[2024-05-19 17:45:57,106][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-19 17:45:58,813][flwr][INFO] - Received initial parameters from one random client
[2024-05-19 17:45:58,813][flwr][INFO] - Evaluating initial parameters
[2024-05-19 17:46:00,710][flwr][INFO] - initial parameters (loss, other metrics): 192.8036768436432, {'accuracy': 0.1034}
[2024-05-19 17:46:00,710][flwr][INFO] - FL starting
[2024-05-19 17:46:00,710][flwr][DEBUG] - fit_round 1: strategy sampled 10 clients (out of 50)
[2024-05-19 17:46:02,314][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
[2024-05-19 17:46:02,708][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
[2024-05-19 17:46:12,949][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
[2024-05-19 17:46:23,435][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
[2024-05-19 17:46:33,916][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
[2024-05-19 17:46:44,408][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
[2024-05-19 17:46:54,883][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=1087133, ip=172.17.34.3)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/rkat6291/flwr_bnn_fromt/client.py", line 89, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/home/rkat6291/flwr_bnn_fromt/model.py", line 55, in train
    for images, labels in trainloader:
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.9/site-packages/torchvision/datasets/mnist.py", line 138, in __getitem__
    img, target = self.data[index], int(self.targets[index])
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float64)
